apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "chart.name" .}}-config
  namespace: {{.Values.namespace}}
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: logviewer-logs
        static_configs:
          - targets:
              - logviewer.kube-system.svc.cluster.local:3000
            labels:
              job: my-app
              __path__: /var/log/pods/my-app_my-app*/*/*.log

          - targets:
              - logviewer.kube-system.svc.cluster.local:3000
            labels:
              job: nginx
              __path__: /var/log/pods/my-app_nginx*/*/*.log