apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{include "chart.name" .}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{include "chart.name" .}}
spec:
  selector:
    matchLabels:
      app: {{include "chart.name" .}}
  template:
    metadata:
      labels:
        app: {{include "chart.name" .}}
    spec:
      serviceAccountName: {{include "chart.name" .}}-sa
      containers:
      - name: {{include "chart.name" .}}
        image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
        args:
          - -config.file=/etc/promtail/promtail.yaml
          - -config.expand-env=true
        volumeMounts:
        - name: config
          mountPath: /etc/promtail
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: {{include "chart.name" .}}-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers