global:

  postgresql:
    enabled: true
    initdb:
      user: "user"
      password: "password"
    auth:
      enablePostgresUser: true
      postgresPassword: "adminpassword"  # Пароль суперпользователя
      username: "user"                   # Имя создаваемого пользователя
      password: "password"               # Пароль создаваемого пользователя
      database: "debug"                  # Имя создаваемой базы данных
    service:
      port: 5432
    persistence:
      enabled: true
      size: 8Gi
      storageClass: "standard"

myapp:
  replicaCount: 1
  image:
    repository: sorokin21/nodejs_test_crud-my_app
    tag: latest
  service:
    port: 4000
  commitHash: 01a3bd1d2fc3bdae9425771a0484c09ecfe25a31

nginx:
  enabled: true
  service:
    type: LoadBalancer
    port: 80
  ingress:
    enabled: true
    hostname: example.com
    tls: false
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "standard"
  serverBlock: |
    server {
      listen 8080;
      location /api/ {
        proxy_pass http://my-app:4000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }