apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.name" . }}
  namespace:  {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "chart.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.myapp.service.port }}
      targetPort: {{ .Values.myapp.service.port }}