---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "chart.name" .}}
  namespace: {{.Values.namespace}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{include "chart.name" .}}
  template:
    metadata:
      labels:
        app: {{include "chart.name" .}}
    spec:
      containers:
      - name: {{include "chart.name" .}}
        image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
        args: ["-config.file=/etc/loki/local-config.yaml"]
        ports:
        - containerPort: {{.Values.service.port}}
        volumeMounts:
        - name: {{include "chart.name" .}}-config
          mountPath: /etc/loki
          readOnly: true
        - name: wal-volume
          mountPath: /wal
      volumes:
      - name: {{include "chart.name" .}}-config
        configMap:
          name: {{include "chart.name" .}}-config
      - name: wal-volume
        emptyDir: {}