apiVersion: v2
name: my-app
version: 1.0.0
dependencies:
  - name: postgresql
    version: 15.5.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: nginx
    version: 18.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: nginx.enabled