apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "chart.name" .}}-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/grafana"