apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "chart.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}