apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.name" .}}-config
  namespace: {{.Values.namespace}}
data:
  prometheus.yml: |-
      global:
        scrape_interval: 5s

      scrape_configs:

        - job_name: 'my_app'
          static_configs:
            - targets: ['my-app.nodejs-app.svc.cluster.local:4000']
        - job_name: 'node-exporter'
          static_configs:
            - targets: ['node-exporter:9100']
              labels:
                service: 'app-exporter'
                group: 'testing'
                name: 'app-exporter'